import '@/models/Artist';
import '@/models/Album';
import '@/models/Song';
import '@/models/Post';
import '@/models/MediaAsset';
import '@/models/Event';
import '@/models/Initiative';
import '@/models/Booking';
import '@/models/Tag';
